apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-profile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-profile
  template:
    metadata:
      labels:
        app: my-profile
    spec:
      containers:
      - name: my-profile-container
        image: your-docker-username/your-docker-repository:your-tag
        ports:
        - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: my-profile-service
spec:
  selector:
    app: my-profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
  type: LoadBalancer
